// menu.js
export const MENU = {
 hot: [
  { id:'h1', ar:'شاي', en:'Tea', img:'photos/tea.jpg', price:'$2.50' },
  { id:'h2', ar:'قهوة', en:'Coffee', img:'photos/coffee.jpg', price:'$3.00' },
  { id:'h3', ar:'زهورات', en:'Herbal Mix', img:'photos/herbal_mix.jpg', price:'$2.75' },
  { id:'h4', ar:'زعتر', en:'Thyme Tea', img:'photos/thyme_tea.jpg', price:'$2.75' },
  { id:'h5', ar:'مليسة', en:'Melissa', img:'photos/melissa.jpg', price:'$2.75' },
  { id:'h6', ar:'يانسون', en:'Anise', img:'photos/anise.jpg', price:'$2.75' },
  { id:'h7', ar:'كمون وليمون', en:'Cumin & Lemon', img:'photos/cumin_lemon.jpg', price:'$3.00' },
  { id:'h8', ar:'نسكافية', en:'Nescafé', img:'photos/nescafe.jpg', price:'$3.25' },
  { id:'h9', ar:'كاكاو', en:'Cocoa', img:'photos/cocoa.jpg', price:'$3.50' },
  { id:'h10', ar:'كابتشينو', en:'Cappuccino', img:'photos/cappuccino.jpg', price:'$4.00' },
  { id:'h11', ar:'نسكافيه 3in1', en:'Nescafé 3in1', img:'photos/nescafe_3in1.jpg', price:'$3.00' },
  { id:'h12', ar:'نسكافية 2in1', en:'Nescafé 2in1', img:'photos/nescafe_2in1.jpg', price:'$2.75' },
  { id:'h13', ar:'كابتشينو تيروبيكا', en:'Cappuccino Tirobica', img:'photos/cappuccino_tirobica.jpg', price:'$4.25' },
  { id:'h14', ar:'شاي اخضر', en:'Green Tea', img:'photos/green_tea.jpg', price:'$2.50' },
  { id:'h15', ar:'زنجبيل وعسل', en:'Ginger & Honey', img:'photos/ginger_honey.jpg', price:'$3.50' },
  { id:'h16', ar:'زنجبيل وحامض وعسل', en:'Ginger Lemon Honey', img:'photos/ginger_lemon_honey.jpg', price:'$3.75' },
  { id:'h17', ar:'لاتيه', en:'Latte', img:'photos/latte.jpg', price:'$4.00' },
  { id:'h18', ar:'امركان كافيه', en:'Americano', img:'photos/americano.jpg', price:'$3.75' },
],

 saj: [
  { id:'s1', ar:'صاج جبنة', en:'Cheese Saj', img:'photos/صاج جبنة.jpg', price:'$5.00' },
  { id:'s2', ar:'صاج زعتر', en:'Za’atar Saj', img:'photos/صاج zaatar.jpg', price:'$4.50' },
  { id:'s3', ar:'صاج حبش وجبنة', en:'Turkey & Cheese Saj', img:'photos/habash.webp', price:'$6.50' },
  { id:'s5', ar:'صاج قشقوان', en:'Kashkaval Saj', img:'photos/صاج قشقوان.jpg', price:'$5.50' },
  { id:'s6', ar:'صاج مرتديلا', en:'Mortadella Saj', img:'photos/صاج مرتديلا.jpg', price:'$6.00' },
  { id:'s7', ar:'صاج لبنة', en:'Labneh Saj', img:'photos/صاج لبنة.webp', price:'$5.00' },
  { id:'s8', ar:'صاج قشقوان وحبش', en:'Kashkaval & Turkey Saj', img:'photos/habash.webp', price:'$7.00' },
  { id:'s9', ar:'صاج قشقوان ومرتديلا', en:'Kashkaval & Mortadella Saj', img:'photos/habashh.webp', price:'$6.75' },
  { id:'s10', ar:'صاج نيوتيلا', en:'Nutella Saj', img:'photos/CHOCO-SAJ.webp', price:'$6.00' },
],

  cocktail: [
    { id: 'k1', ar: 'عصير برتقال', en: 'Orange Juice', price: '$4.00' },
    { id: 'k3', ar: 'عصير جزر', en: 'Carrot Juice', price: '$4.00' },
    { id: 'k4', ar: 'عصير تفاح', en: 'Apple Juice', price: '$4.50' },
    { id: 'k5', ar: 'ليموناضة', en: 'Lemonade', price: '$5.00' },
    { id: 'k6', ar: 'ليموناضة ونعنع', en: 'Lemonade Mint', price: '$5.50' },
    { id: 'k7', ar: 'حليب وموز', en: 'Milk & Banana Shake', price: '$5.00' },
    { id: 'k8', ar: 'كوكتيل فواكه', en: 'Fruit Cocktail', price: '$6.00' },
    { id: 'k9', ar: 'عصير فريز', en: 'Strawberry Juice', price: '$5.00' },
    { id: 'k10', ar: 'عصير منغا', en: 'Mango Juice', price: '$5.50' },
    { id: 'k11', ar: 'عصير اناناس', en: 'Pineapple Juice', price: '$5.50' },
    { id: 'k12', ar: 'فريز وحليب', en: 'Strawberry Milkshake', price: '$5.25' },
    { id: 'k13', ar: 'عصير افوكا', en: 'Avocado Juice', price: '$6.00' },
    { id: 'k14', ar: 'كوكتيل اروما', en: 'Aroma Cocktail', price: '$6.50' },
  ],
  shisha: [
    { id: 'sh1', ar: 'ارغيلة تفاحتين', en: 'Double Apple Shisha', img: 'photos/tefehten.avif', price: '$10.00' },
    { id: 'sh2', ar: 'ارغيلة عنب', en: 'Grape Shisha', img: 'photos/eeenab.jpg', price: '$10.00' },
    { id: 'sh3', ar: 'ارغيلة عنب ونعنع', en: 'Grape Mint Shisha', img: 'photos/eenab.jpg', price: '$11.00' },
    { id: 'sh4', ar: 'ارغيلة حامض ونعنع', en: 'Lemon Mint Shisha', img: 'photos/hamd nana.avif', price: '$11.00' },
    { id: 'sh5', ar: 'ارغيلة Love', en: 'Love Shisha', img: '', price: '$12.00' },
    { id: 'sh6', ar: 'ارغيلة عجمي', en: 'Ajami Shisha', img: 'photos/aajami.jpg', price: '$10.00' },
    { id: 'sh7', ar: 'خدمة ارغيلة عجمي', en: 'Ajami Shisha Service', img: 'photos/aajami.jpg', price: '$13.00' },
  ],
 snacks: [
  { ar:'ببسي', en:'Pepsi', img:'photos/pepsi.avif', price:'$2.00' },
  { ar:'سفن اب', en:'7UP', img:'photos/7up-.webp', price:'$2.00' },
  { ar:'ميرندا', en:'Mirinda', img:'photos/miranda.avif', price:'$2.00' },
  { ar:'لبن', en:'Laban', img:'photos/laban.webp', price:'$2.50' },
  { ar:'بوم بوم', en:'Boom Boom', img:'photos/boom boom', price:'$3.00' },
  { ar:'رد بول', en:'Red Bull', img:'photos/redbull.avif', price:'$4.00' },
  { ar:'دارك بلو', en:'Dark Blue', img:'photos/db.png', price:'$3.50' },
  { ar:'ايس تي', en:'Ice Tea', img:'photos/ice tea.avif', price:'$3.00' },
  { ar:'ايس كوفي', en:'Ice Coffee', img:'photos/ice coffe.jpg', price:'$3.50' },
  { ar:'فرييز', en:'Freeze', img:'photos/freeze.jpg', price:'$3.00' },
  { ar:'ملك شيك', en:'Milkshake', img:'photos/milkshake.jpg', price:'$5.00' },
  { ar:'ريندو', en:'Rindo', img:'photos/rindo.avif', price:'$2.50' },
  { ar:'الوفيرا', en:'Aloe Vera', img:'photos/aloevera.avif', price:'$3.00' },
  { ar:'ريم غازية', en:'Rim Sparkling', img:'photos/rim sp.avif', price:'$2.50' },
  { ar:'مياه ص', en:'Water Small', img:'photos/water small.webp', price:'$1.00' },
  { ar:'مياه ك', en:'Water ', img:'photos/water big.jpg', price:'$1.50' },
  { ar:'ريمfruits ', en:'Rim Fruits ', img:'photos/Rim-Web-RXF-A.jpg', price:'$2.75' },
  { ar:'مارس', en:'Mars', img:'photos/mars_twix_white_58g_prod-500x500.jpg', price:'$2.00' },
  { ar:'سنكرز', en:'Snickers', img:'photos/snickers.webp', price:'$2.00' },
  { ar:'البيني', en:'Albini', img:'photos/albeni.avif', price:'$2.50' },
  { ar:'البيني كيك', en:'Albini Cake', img:'photos/cake albeni.avif', price:'$3.00' },
  { ar:'باونتي', en:'Bounty', img:'photos/bounty.jpg', price:'$2.00' },
  { ar:'تويكس', en:'Twix', img:'photos/twix.jpg', price:'$2.00' },
  { ar:'كيندر', en:'Kinder', img:'photos/kinder-chocolate-8-pack.jpg', price:'$2.50' },
  { ar:'كيت كات', en:'KitKat', img:'photos/kitkat.avif', price:'$2.00' },
  { ar:'كيندر دليس', en:'Kinder Delice', img:'photos/kinder delice.jpg', price:'$2.75' },
  { ar:'نسلة', en:'Nestlé', img:'photos/nestle.avif', price:'$2.00' },
  { ar:'نسكويك', en:'Nesquik', img:'photos/nesquik.webp', price:'$2.00' },
  { ar:'ستارز', en:'Stars', img:'photos/stars.avif', price:'$2.00' },
  { ar:'شوكوبرنس', en:'Choco Prince', img:'photos/choco prince.jpg', price:'$1.75' },
  { ar:'اونيكا', en:'Onika', img:'photos/unica.jpg', price:'$2.00' },
  { ar:'ريماس كيك', en:'Rimas Cake', img:'photos/rimas cake.jpg', price:'$2.25' },
  { ar:'ريماس براوني', en:'Rimas Brownie', img:'photos/rimas brownie.jpg', price:'$2.50' },
  { ar:'ريماس تمر', en:'Rimas Date Bar', img:'photos/rimas date.jpg', price:'$2.50' },
],

};
